### ISSUE TITLE
Support for SVG-Sprites would be awesome

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Neos.PreviewSelectBox#1]
This would be a nice way to support Fontawesome-Pro Icons in the Neos Backend @Sebobo

**Comment by Sebobo** [comment]
You can add them as individual SVGs to your project and use those. As the preview component only accepts standard FA icons and image Uris, there is not much more that I could do.

**Comment by paavo** [comment]
Thanks for the hint @Sebobo 
Let me try how long it takes to load a Resource (SVG Image) for every Icon in the long list of icons 🙈  

Mabye it's easier to replace Fontawesome free with Pro in Neos Backend 🤔

**Comment by Sebobo** [comment]
Can't you use https://github.com/sitegeist/Sitegeist.Stampede ?

**Comment by paavo** [comment]
Thanks for the hint @Sebobo - i'll give it a try 🤩

**Comment by Sebobo** [comment]
I'll not add anything new to this package as the feature is in the core, so I'll close this.
